config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do
      get :autocomplete
    end
  end
  resources :images do
    member do
      delete :delete_image   #to delete image which is inside image_name
      delete :delete_documents  #to delete documents images 
    end
  end
  resources :users
end

app/models/product.rb
class Product < ApplicationRecord
    searchkick text_middle: [:name, :details]
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    search = params[:query].present? ? params[:query] : nil
    @products = if search
      # Product.search(search)
      Product.search(search, fields: [{name: :text_middle}, {details: :text_middle}])
    else
      Product.all
    end
    
    @products_name = Product.all.pluck(:name)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def autocomplete
    
    # binding.pry
    
    render json: Product.search(params[:query], fields: ["name", "details"],match: :text_middle,limit: 10,load: false, misspellings: {below: 5}).map(&:name)
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :details, :brand, :price)
    end
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :details, style: "display: block" %>
    <%= form.text_field :details %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= product.details %>
  </p>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<div class="col-4" id="bloodhound" >
    <%= form_tag products_path, :method => 'get' ,local:true do %>
      <%= text_field_tag :query, params[:query], id:"query", class:"typeahead", placeholder: 'Search email is present or not' %>
        <span>
          <%= submit_tag "search"%>
        </span>
    <% end %>
  </div>
<!--<div id="bloodhound">
  <input class="typeahead" type="text" placeholder="States of USA">
</div>-->
<br><br><br><br>
<%=@products_name%>
<h1>product Table </h1>
<table>
  <tr>
    <td>product Name</td>
    <td>isbn</td>
    <% @products.each do |product| %>
  <tr>
    <td>
      <%=product.name %>
    </td>
    <td>
      <%=product.details %>
    </td>
  </tr>
  <% end %>
</table>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<%= render 'typeaheaad_bundle_js'%>
<script>
// console.log("index");
//   var states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
//     'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii',
//     'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
//     'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
//     'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
//     'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
//     'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
//     'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
//     'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
//   ];
//   var states = new Bloodhound({
//     datumTokenizer: Bloodhound.tokenizers.whitespace,
//     queryTokenizer: Bloodhound.tokenizers.whitespace,
//     `states` is an array of state names defined in "The Basics"
//     local: states
//   });

//   $('#bloodhound .typeahead').typeahead({
//     hint: true,
//     highlight: true,
//     minLength: 1
//   },
//   {
//     name: 'states',
//     source: states
//   });
// var p2 = new Array();
// <% @products_name.each do |i|%>
//   p2.push("<%=i%>")
// <% end %>
//   var products = p2;
//   products = new Bloodhound({
//     datumTokenizer: Bloodhound.tokenizers.whitespace,
//     queryTokenizer: Bloodhound.tokenizers.whitespace,
//     local: products
//   });
//   $('#bloodhound .typeahead').typeahead({
//     hint: true,
//     highlight: true,
//     minLength: 1
//   },
//   {
//     name: 'products',
//     source: products
//   });

//-------------------autocomplete---------------------
 var products = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: '/products/autocomplete?query=%QUERY',
      wildcard: '%QUERY'
    }
  });
  $('#query').typeahead(null, {
    highlight: true,
    source: products
  });
</script>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>