config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do
      get :autocomplete
    end
  end
  resources :images do
    member do
      delete :delete_image   #to delete image which is inside image_name
      delete :delete_documents  #to delete documents images 
    end
  end
  resources :users
end

app/models/image.rb
class Image < ApplicationRecord
    has_one_attached :image_name
    # def image_as_thumbnail
    #     image_name.variant(resize_to_limit: [300, 300]).processed
    # end

    has_one_attached :image_name do |attachable|
        attachable.variant :thumb, resize_to_limit: [300, 300]
    end

        has_many_attached :documents

    has_many_attached :documents do |attachable|
        attachable.variant :thumb, resize_to_limit: [200, 200]
    end
    has_one_attached :file_name
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    @pre_values = Image.find(params[:id])
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    @image.update(image_params)
    
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_image
    @image = Image.find(params[:id])
    @image.image_name.purge_later
    redirect_back fallback_location: images_path
  end

  def delete_documents
    @image = Image.find(params[:id])
    @image.documents.where("id = ?",params[:doc_id]).purge
    redirect_back fallback_location: images_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:image_name,:file_name, documents: [])
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image_name, style: "display: block" %>
    <%= form.file_field :image_name %>
  </div>
  <%#= form.hidden_field :pre_name, value: form.object.image_name if form.object.image_name.attached? %>
  <div>
    <%= form.label :documents, style: "display: block" %>
    <%= form.file_field :documents, multiple: true %>
  </div>
  <div>
    <%= form.label :file_name, style: "display: block" %>
    <%= form.file_field :file_name, accept: "application/pdf" %>
  </div>
 <%#= form.hidden_field :pre_file, value: form.object.file_name if form.object.file_name.attached? %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
   
    <%#= image_tag(image.image_name) %>
    <%#= image_tag image.image_name.variant( saver: { quality: 30}) %>
    <%#= link_to image_tag(image.image_as_thumbnail), image.image_name %>
    <% if image.image_name.attached?%>
       <strong>Image:</strong><br>
      <%= link_to image_tag image.image_name.variant(:thumb) %><br>
      <%= link_to 'Download Image', image.image_name, download: 'data' %><br>
      <%= button_to 'delete image',delete_image_image_path(image), method: :delete %>
    <% end %>
     <% if image.file_name.attached?%>
       <strong>file:</strong><br>
      <%#= link_to image_tag image.image_name.variant(:thumb) %><br>
      <%= link_to 'Download file', image.file_name, download: 'data' %><br>
      <%= link_to 'View  file', image.file_name %><br>
      <%#= button_to 'delete image',delete_image_image_path(image), method: :delete %>
    <% end %>
    <% if image.documents.attached?%>
        <strong>Documents:</strong><br>
      <% image.documents.each do |doc|%>
        <%#= image_tag(doc)%>  
        <%= image_tag doc.variant(:thumb) %>
        <%= link_to 'Download Image', doc, download: 'data' %><br>
        <%= button_to 'delete document',delete_documents_image_path(image), method: :delete, params: { doc_id:doc.id} %>
      <<% end %>%>
    <% end %>
  </p>

</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Images</h1>

<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
    <p>
      <%= link_to "Show this image", image %>
    </p>
  <% end %>
</div>

<%= link_to "New image", new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>